```{r}
library(tidyverse)
library(dbscan)

files<-list.files("/media/Lawrenson_Lab_NAS/uthscsa/group_data/CosMx_temp",full.names = T)
files<-files[str_detect(files,"SL")]
files<-list.files(files,full.names = T)
files<-files[str_detect(files,"csv")]
data<-lapply(files,data.table::fread)
#8.5 GB 
names(data)<-str_remove_all(files,".+temp\\/|.pix.+")

data<-lapply(data,function(x) 
  x%>%mutate(across(PGP95:CD20,function(x) asinh(x/5))))
#should robustly scale using the 1st–99th percentiles instead
data<-lapply(data,function(x) 
    x%>%mutate(across(PGP95:CD20,function(x) (x-quantile(x,.01))/(quantile(x,.99)-quantile(x,.01)))))
data<-lapply(data,function(x) 
  x%>%mutate(across(PGP95:CD20,function(x) case_when(x>1~1,x<0~0,TRUE~x))))

```

```{r}
filtered<-lapply(data,function(x)
  x%>%pivot_longer(PGP95:CD20,names_to = "protein",values_to = "signal"))
filtered<-lapply(filtered,function(x) 
  x%>%filter(signal>.9)%>%add_count(x,y)%>%filter(n<3))
filtered<-lapply(filtered,function(x) 
  x%>%group_by(x,y)%>%
  group_by(x,y)%>%mutate(pair=ifelse(n==2,
                     paste(unique(protein),collapse = ','),
                     "single"))%>%ungroup)
filtered<-lapply(filtered,function(x)
  x%>%filter(pair%in%c("single","CD45,CD20")))

positives<-lapply(filtered,function(x)
  x%>%filter((pair=="single"&!protein%in%c("CD45","CD20"))|
           (protein=="CD20"&pair!="single"))%>%filter(signal==1))

```

```{r}

for(i in 1:length(filtered)){
  positives[[i]]$cl<-dbscan(positives[[i]][,1:2],
                           minPts = 2,
                           eps = 100,
                           borderPoints = F)$cluster}
positives<-lapply(positives,function(x)
      x%>%select(-n)%>%add_count(cl,protein)%>%
        group_by(protein)%>%filter(n<quantile(n,.9)|!protein%in%c("PGP95","CD20"))
      
temp<-as.data.frame(cbind(Sample=names(data),
                          total=sapply(data,nrow),
                          thr_1=sapply(filtered,nrow),
                          thr_2=sapply(positives,nrow),
                          PGP95_pos=sapply(positives,function(x) 
                            x%>%filter(protein=="PGP95")%>%nrow())))

visual_inspection<-function(samp){
  plots<-lapply(c("CD10","KRT8","CD45","CD20","PGP95"),function(z) 
    filtered[[samp]]%>%filter(protein==z)%>%ggplot(aes(x=x,y=-y,col=signal))+
    geom_point(size=.1)+scale_color_viridis_c(option = 'H')+ggtitle(z))
  plots[[6]]<-positives[[samp]]%>%
    ggplot(aes(x=x,y=-y,col=protein))+geom_point(size=.1)+
    guides(col=guide_legend(override.aes = list(size=5)))
  gridExtra::grid.arrange(grobs=plots)}
```

```{r}
centr<-lapply(positives,function(x) 
  x%>%group_by(cl,protein)%>%
  summarise(x=median(x),y=median(y),n=n()))
temp<-lapply(names(data),function(i) 
  centr[[i]]%>%mutate(Sample=i))%>%bind_rows()%>%
  group_by(Sample,protein)%>%filter(n>2)%>%#arbitrary threshold
  summarise(LA_size=sum(n),LA_total=n())%>%
  filter(protein=="CD20")%>%ungroup()%>%select(-protein)%>%
  right_join(temp)


mat<-lapply(1:length(positives),function(z)
  apply(centr[[z]],1,function(x) 
    apply(centr[[z]]%>%filter(protein=="CD20"),1,function(y) sqrt((as.numeric(x[3])-as.numeric(y[3]))**2+(as.numeric(x[4])-as.numeric(y[4]))**2))))
for(i in 1:length(filtered)){
  centr[[i]]$min_dist_to_LA<-apply(mat[[i]], 2,min)}
lapply(centr,function(x)
  x%>%group_by(protein)%>%summarise(min_dist_to_LA=mean(min_dist_to_LA)))

```